"""add season column

Revision ID: 363879f78176
Revises: 
Create Date: 2025-08-04 22:37:09.753622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363879f78176'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('flag', sa.String(length=255), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('is_european_top_league', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('birth_country', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('height', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.String(length=10), nullable=True),
    sa.Column('injured', sa.Boolean(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('national', sa.Boolean(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('venue_name', sa.String(length=100), nullable=True),
    sa.Column('venue_address', sa.String(length=255), nullable=True),
    sa.Column('venue_city', sa.String(length=50), nullable=True),
    sa.Column('venue_capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('loaned_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('parent_team_id', sa.Integer(), nullable=False),
    sa.Column('loan_team_id', sa.Integer(), nullable=False),
    sa.Column('loan_start_date', sa.Date(), nullable=False),
    sa.Column('loan_end_date', sa.Date(), nullable=True),
    sa.Column('original_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('loan_fee', sa.Float(), nullable=True),
    sa.Column('buy_option_fee', sa.Float(), nullable=True),
    sa.Column('buy_option_deadline', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True),
    sa.Column('loan_season', sa.String(length=10), nullable=True),
    sa.Column('early_termination', sa.Boolean(), nullable=True),
    sa.Column('termination_reason', sa.String(length=200), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('recall_option', sa.Boolean(), nullable=True),
    sa.Column('performance_notes', sa.Text(), nullable=True),
    sa.Column('last_performance_update', sa.DateTime(), nullable=True),
    sa.Column('appearances', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['parent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('newsletter_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_content', sa.Text(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('week_end_date', sa.Date(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_date', sa.DateTime(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('generated_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('preferred_frequency', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=100), nullable=True),
    sa.Column('last_email_sent', sa.DateTime(), nullable=True),
    sa.Column('bounce_count', sa.Integer(), nullable=True),
    sa.Column('email_bounced', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscriptions')
    op.drop_table('newsletters')
    op.drop_table('loaned_players')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_table('leagues')
    # ### end Alembic commands ###
